%% TO DO
% - where/how to store model information and parameter values for noise correlation & coupling matrix in the saved mat-file?
% - fill struct file in a loop?
% - add integrated information measures?

%% 8-NODE MULTIVARIATE AUTOREGRESSIVE TIME-SERIES (MVAR) WITH GLOBAL COUPLING FACTORS & DIFFERENT MACRO VARIABLES

% This script implements synergy capacity for 8-node MVAR models with different global coupling factors and noise correlations, and two different macro variables 
% (one time being a summation of the raw values of X, and one time being a summation of the exponential of X).

% The main purpose is to investigate the effect of doing a bipartition in PhiID: we simulate a network with the a given
% set of parameters, then form all possible sets of two nodes, calculate integrated information for each of them, 
% and choose those two nodes which yield the MIB. PhiID-based (as well as practical) causal emergence is then 
% calculated. We use the same procedure for, three, four, etc. up to eight nodes.

clear all;
clear java;
close all;
clc;

cd '/media/nadinespy/NewVolume/my_stuff/work/PhD/my_projects/EmergenceComplexityMeasuresComparison/EmergenceComplexityMeasuresComparison_Matlab/scripts'
addpath '/media/nadinespy/NewVolume/my_stuff/work/toolboxes_matlab'
addpath '/media/nadinespy/NewVolume/my_stuff/work/PhD/my_projects/EmergenceComplexityMeasuresComparison/EmergenceComplexityMeasuresComparison_Matlab/scripts/ReconcilingEmergences-master'
javaaddpath('infodynamics.jar');

pathout_data = '/media/nadinespy/NewVolume/my_stuff/work/PhD/my_projects/EmergenceComplexityMeasuresComparison/EmergenceComplexityMeasuresComparison_Matlab/results/analyses/8node_mvar_global_coupling/';
pathout_plots = '/media/nadinespy/NewVolume/my_stuff/work/PhD/my_projects/EmergenceComplexityMeasuresComparison/EmergenceComplexityMeasuresComparison_Matlab/results/plots/8node_mvar_global_coupling/';

%% choice of parameters

% time-lag and number of data points in time-series (same for all simulations)
npoints = 2000;
tau = 1;

% simulation method (options: statdata_coup_errors1(), statdata_coup_errors2(), statdata_random(), chimera_metastable_model())
sim_method = @statdata_coup_errors1;

% save plots & matrices according to simulation method (options: '1' (for statdata_coup_errors1()), '2' (for statdata_coup_errors2()), '3' (for statdata_random(), '4' (for metastable_chimera_model())
sim_index = '1';

% network (options: '2node_mvar' for 2-node network with 100 different coupling strengths & noise correlations (if choosing sim_index = 1 or 2) OR random 2-node network with 100 zero couplings & 100 zero noise correlations (if choosing sim_index = 3);
% '8node_mvar_different_architectures' for 8-node networks with 6 different architectures & noise correlations (if choosing sim_index = 1 or 2) OR random 8-node networks with 100 zero couplings & 100 zero correlations (if choosing sim_index = 3));
% '8node_mvar_erdoes_renyi' for 8-node Erdös-Renyi networks with 100 different densities & noise correlations (if choosing sim_index = 1 or 2)
% '8node_mvar_global_coupling' for phi-optimal network with 100 different global coupling factors & noise correlations (if choosing sim_index = 1 or 2)
% '8node_kuramoto' for metastable chimera states with 100 different intra- and intercommunity coupling strengths & betas (if choosing sim_index = 4) 
% '256node_kuramoto' for metastable chimera states with 100 different intra- and intercommunity coupling strengths & betas (if choosing sim_index = 5) 

network = '8node_mvar_global_coupling';

%% load files (if already existent, to, e. g., only create plots)

%{

load([pathout_data network '_emergence_ccs' sim_index '.mat'], 'emergence_ccs');
load([pathout_data network '_emergence_mmi' sim_index '.mat'], 'emergence_mmi');
load([pathout_data network '_emergence_practical' sim_index '.mat'], 'emergence_practical');
load([pathout_data network '_all_atoms_err_coup_ccs' sim_index '.mat'], 'all_atoms_err_coup_ccs');
load([pathout_data network '_all_atoms_err_coup_mmi' sim_index '.mat'], 'all_atoms_err_coup_mmi');
load([pathout_data network '_all_average_corr_X' sim_index '.mat'], 'all_average_corr_X');
load([pathout_data network '_all_average_cov_X' sim_index '.mat'], 'all_average_cov_X');

synergy_capacity_mmi = emergence_mmi.synergy_capacity_mmi;
downward_causation_mmi = emergence_mmi.downward_causation_mmi;
causal_decoupling_mmi = emergence_mmi.causal_decoupling_mmi;

synergy_capacity_ccs = emergence_ccs.synergy_capacity_ccs;
downward_causation_ccs = emergence_ccs.downward_causation_ccs;
causal_decoupling_ccs = emergence_ccs.causal_decoupling_ccs;

synergy_capacity_practical_linear = emergence_practical.synergy_capacity_practical_linear; 
downward_causation_practical_linear = emergence_practical.downward_causation_practical_linear; 
causal_decoupling_practical_linear = emergence_practical.causal_decoupling_practical_linear;

synergy_capacity_practical_exponential = emergence_practical.synergy_capacity_practical_exponential; 
downward_causation_practical_exponential = emergence_practical.downward_causation_practical_exponential; 
causal_decoupling_practical_exponential = emergence_practical.causal_decoupling_practical_exponential;

%}

%% create coupling matrices & noise correlation vectors

% {

% networks in all_nets.mat: phi-optimal binary network, phi-optimal weighted network, small world, 
% fully connected, bidirectional ring, unidirectional ring
load('all_nets.mat');								
net_names = fields(all_nets);
optimalB_net = all_nets.OptimalB;
coupling_vec = linspace(0.05,0.9, 100);
error_vec = linspace(0.01, 0.9, 100);
coupling_matrices = [];
	
% optimalB_net(optimalB_net ~= 0) = 1;				% Pedro took the original weighted network as opposed to a binary one --> why should I opt for one or the other? this decision completely changes results for some measures 
k_vec = linspace(0.01, 0.9, 100000);

for i = 1:length(k_vec)
	sr = max(abs(eig(k_vec(i) * optimalB_net)));
	if sr >= 1
		sr = max(abs(eig(k_vec(i-1) * optimalB_net)));
		k_max = k_vec(i-1);
		break
	else k_max = k_vec(i);
	end
end

for o = 1:length(coupling_vec);
	coupling_matrices(:,:,o) = k_max * coupling_vec(o) * optimalB_net;
end


%% calculating information atoms & practical measures

% {

rng(1);
all_phiids = {};
for i = 1:size(coupling_matrices, 3);
	
	coupling_matrix = coupling_matrices(:,:,i);
	disp(i)
	
	for j = 1:length(error_vec)
		
		err = error_vec(j);
		
		X = sim_method(coupling_matrix, npoints, tau, err);
		
		% practical measures for causal emergence - some super simple meaningless macro variable: 
		% adding up the micro one time using the raw values of X, one time using the exponential of X
		variable_index = 1:8;
		
		for k = 2:length(variable_index)
			all_combos = nchoosek(variable_index, k);
			phi = [];
			for g = 1:size(all_combos,1);
				X_temp = X(all_combos(g,:),:);
				
				% create copy of the data scaled to unit variance (for numerical stability)
				sX = X_temp./repmat(std(X_temp')', [1, npoints]);

				% use JIDT to compute Phi
				phiCalc = javaObject('infodynamics.measures.continuous.gaussian.IntegratedInformationCalculatorGaussian');
				if tau > 1
					phiCalc.setProperty(phiCalc.PROP_TAU, num2str(tau));
				end
				phi(g) = phiCalc.compute(octaveToJavaDoubleMatrix(sX'));
				
			end 
			
			[M, I] = min(phi);
			X_temp = X(all_combos(I,:),:);
			
			macro_variable_linear = zeros(1, npoints);
			for f = 1:(size(X_temp,1));
				macro_variable_linear = macro_variable_linear + X_temp(f,:);
			end
			
			if k == 2;
				[phiid_all_err_coup_mmi_two_var(:,i,j)] = struct2array(PhiIDFull(X_temp, tau, 'MMI'))';
				[phiid_all_err_coup_ccs_two_var(:,i,j)] = struct2array(PhiIDFull(X_temp, tau, 'ccs'))';

				synergy_capacity_practical_linear_two_var(i,j) = EmergencePsi(X_temp', macro_variable_linear');
				downward_causation_practical_linear_two_var(i,j) = EmergenceDelta(X_temp', macro_variable_linear');
				causal_decoupling_practical_linear_two_var(i,j) = synergy_capacity_practical_linear_two_var(i,j) - downward_causation_practical_linear_two_var(i,j);
		
			elseif k == 3; 
				[phiid_all_err_coup_mmi_three_var(:,i,j)] = struct2array(PhiIDFull(X_temp, tau, 'MMI'))';
				[phiid_all_err_coup_ccs_three_var(:,i,j)] = struct2array(PhiIDFull(X_temp, tau, 'ccs'))';
				
				synergy_capacity_practical_linear_three_var(i,j) = EmergencePsi(X_temp', macro_variable_linear');
				downward_causation_practical_linear_three_var(i,j) = EmergenceDelta(X_temp', macro_variable_linear');
				causal_decoupling_practical_linear_three_var(i,j) = synergy_capacity_practical_linear_three_var(i,j) - downward_causation_practical_linear_three_var(i,j);
				
			elseif k == 4; 
				[phiid_all_err_coup_mmi_four_var(:,i,j)] = struct2array(PhiIDFull(X_temp, tau, 'MMI'))';
				[phiid_all_err_coup_ccs_four_var(:,i,j)] = struct2array(PhiIDFull(X_temp, tau, 'ccs'))';
				
				synergy_capacity_practical_linear_four_var(i,j) = EmergencePsi(X_temp', macro_variable_linear');
				downward_causation_practical_linear_four_var(i,j) = EmergenceDelta(X_temp', macro_variable_linear');
				causal_decoupling_practical_linear_four_var(i,j) = synergy_capacity_practical_linear_four_var(i,j) - downward_causation_practical_linear_four_var(i,j);
	
			elseif k == 5; 
				[phiid_all_err_coup_mmi_five_var(:,i,j)] = struct2array(PhiIDFull(X_temp, tau, 'MMI'))';
				[phiid_all_err_coup_ccs_five_var(:,i,j)] = struct2array(PhiIDFull(X_temp, tau, 'ccs'))';
				
				synergy_capacity_practical_linear_five_var(i,j) = EmergencePsi(X_temp', macro_variable_linear');
				downward_causation_practical_linear_five_var(i,j) = EmergenceDelta(X_temp', macro_variable_linear');
				causal_decoupling_practical_linear_five_var(i,j) = synergy_capacity_practical_linear_five_var(i,j) - downward_causation_practical_linear_five_var(i,j);
	
			elseif k == 6; 
				[phiid_all_err_coup_mmi_six_var(:,i,j)] = struct2array(PhiIDFull(X_temp, tau, 'MMI'))';
				[phiid_all_err_coup_ccs_six_var(:,i,j)] = struct2array(PhiIDFull(X_temp, tau, 'ccs'))';
		
				synergy_capacity_practical_linear_six_var(i,j) = EmergencePsi(X_temp', macro_variable_linear');
				downward_causation_practical_linear_six_var(i,j) = EmergenceDelta(X_temp', macro_variable_linear');
				causal_decoupling_practical_linear_six_var(i,j) = synergy_capacity_practical_linear_six_var(i,j) - downward_causation_practical_linear_six_var(i,j);
	
			elseif k == 7; 
				[phiid_all_err_coup_mmi_seven_var(:,i,j)] = struct2array(PhiIDFull(X_temp, tau, 'MMI'))';
				[phiid_all_err_coup_ccs_seven_var(:,i,j)] = struct2array(PhiIDFull(X_temp, tau, 'ccs'))';
				
				synergy_capacity_practical_linear_seven_var(i,j) = EmergencePsi(X_temp', macro_variable_linear');
				downward_causation_practical_linear_seven_var(i,j) = EmergenceDelta(X_temp', macro_variable_linear');
				causal_decoupling_practical_linear_seven_var(i,j) = synergy_capacity_practical_linear_seven_var(i,j) - downward_causation_practical_linear_seven_var(i,j);
	
			elseif k == 8; 
				[phiid_all_err_coup_mmi_eight_var(:,i,j)] = struct2array(PhiIDFull(X_temp, tau, 'MMI'))';
				[phiid_all_err_coup_ccs_eight_var(:,i,j)] = struct2array(PhiIDFull(X_temp, tau, 'ccs'))';
				
				synergy_capacity_practical_linear_eight_var(i,j) = EmergencePsi(X_temp', macro_variable_linear');
				downward_causation_practical_linear_eight_var(i,j) = EmergenceDelta(X_temp', macro_variable_linear');
				causal_decoupling_practical_linear_eight_var(i,j) = synergy_capacity_practical_linear_eight_var(i,j) - downward_causation_practical_linear_eight_var(i,j);
			end

		end 
		
		% average covariance/correlation matrix
		cov_X = cov(X');
		all_average_cov_X(i,j) = mean(nonzeros(tril(cov_X,-1)), 'all');
			
		corr_X = corrcov(cov_X);
		all_average_corr_X(i,j) = mean(nonzeros(tril(corr_X,-1)), 'all');
	
	end 

end 

%% storing information atoms in struct files

% information atoms: extract single atoms such that rows are the couplings, and columns the errors

% rtr:  {1}{2}-->{1}{2}
% rtx: {1}{2}-->{1}
% rty: {1}{2}-->{2}
% rts: {1}{2}-->{12}
% xtr: {1}-->{1}{2}
% xtx: {1}-->{1}
% xty: {1}-->{2} 
% xts: {1}-->{12}
% ytr: {2}-->{1}{2}
% ytx: {2}-->{1}
% yty: {2}-->{2}
% yts: {2}-->{12} 
% str: {12}-->{1}{2}
% stx: {12}-->{1} 
% sty: {12}-->{2} 
% sts: {12}-->{12}

[all_atoms_err_coup_mmi_two_var, all_atoms_err_coup_ccs_two_var] =  store_atoms_in_struct(phiid_all_err_coup_mmi_two_var, phiid_all_err_coup_ccs_two_var);
[all_atoms_err_coup_mmi_three_var, all_atoms_err_coup_ccs_three_var] =  store_atoms_in_struct(phiid_all_err_coup_mmi_three_var, phiid_all_err_coup_ccs_three_var);
[all_atoms_err_coup_mmi_four_var, all_atoms_err_coup_ccs_four_var] =  store_atoms_in_struct(phiid_all_err_coup_mmi_four_var, phiid_all_err_coup_ccs_four_var);
[all_atoms_err_coup_mmi_five_var, all_atoms_err_coup_ccs_five_var] =  store_atoms_in_struct(phiid_all_err_coup_mmi_five_var, phiid_all_err_coup_ccs_five_var);
[all_atoms_err_coup_mmi_six_var, all_atoms_err_coup_ccs_six_var] =  store_atoms_in_struct(phiid_all_err_coup_mmi_six_var, phiid_all_err_coup_ccs_six_var);
[all_atoms_err_coup_mmi_seven_var, all_atoms_err_coup_ccs_seven_var] =  store_atoms_in_struct(phiid_all_err_coup_mmi_seven_var, phiid_all_err_coup_ccs_seven_var);
[all_atoms_err_coup_mmi_eight_var, all_atoms_err_coup_ccs_eight_var] =  store_atoms_in_struct(phiid_all_err_coup_mmi_eight_var, phiid_all_err_coup_ccs_eight_var);

save([pathout_data network '_all_atoms_err_coup_ccs_two_var_' sim_index '.mat'], 'all_atoms_err_coup_ccs_two_var');
save([pathout_data network '_all_atoms_err_coup_mmi_two_var_' sim_index '.mat'], 'all_atoms_err_coup_mmi_two_var');

save([pathout_data network '_all_atoms_err_coup_ccs_three_var_' sim_index '.mat'], 'all_atoms_err_coup_ccs_three_var');
save([pathout_data network '_all_atoms_err_coup_mmi_three_var_' sim_index '.mat'], 'all_atoms_err_coup_mmi_three_var');

save([pathout_data network '_all_atoms_err_coup_ccs_four_var_' sim_index '.mat'], 'all_atoms_err_coup_ccs_four_var');
save([pathout_data network '_all_atoms_err_coup_mmi_four_var_' sim_index '.mat'], 'all_atoms_err_coup_mmi_four_var');

save([pathout_data network '_all_atoms_err_coup_ccs_five_var_' sim_index '.mat'], 'all_atoms_err_coup_ccs_five_var');
save([pathout_data network '_all_atoms_err_coup_mmi_five_var_' sim_index '.mat'], 'all_atoms_err_coup_mmi_five_var');

save([pathout_data network '_all_atoms_err_coup_ccs_six_var_' sim_index '.mat'], 'all_atoms_err_coup_ccs_six_var');
save([pathout_data network '_all_atoms_err_coup_mmi_six_var_' sim_index '.mat'], 'all_atoms_err_coup_mmi_six_var');

save([pathout_data network '_all_atoms_err_coup_ccs_seven_var_' sim_index '.mat'], 'all_atoms_err_coup_ccs_seven_var');
save([pathout_data network '_all_atoms_err_coup_mmi_seven_var_' sim_index '.mat'], 'all_atoms_err_coup_mmi_seven_var');

save([pathout_data network '_all_atoms_err_coup_ccs_eight_var_' sim_index '.mat'], 'all_atoms_err_coup_ccs_eight_var');
save([pathout_data network '_all_atoms_err_coup_mmi_eight_var_' sim_index '.mat'], 'all_atoms_err_coup_mmi_eight_var');

%}

%% phiid-based synergistic/emergent capacity, downward causation, causal decoupling

% {
% calculate:
% Syn(X_t;X_t-1) (synergistic capacity of the system) 
% Un (Vt;Xt'|Xt) (causal decoupling - the top term in the lattice) 
% Un(Vt;Xt'α|Xt) (downward causation) 

% synergy (only considering the synergy that the sources have, not the target): 
% {12} --> {1}{2} +
% {12} --> {1} + 
% {12} --> {2} +
% {12} --> {12} 
 
% causal decoupling: {12} --> {12}

% downward causation: 
% {12} --> {1}{2} + 
% {12} --> {1} + 
% {12} --> {2}

% synergistic capacity

[synergy_capacity_mmi_two_var, ...
	downward_causation_mmi_two_var, ...
	causal_decoupling_mmi_two_var, ...
	synergy_capacity_ccs_two_var, ...
	downward_causation_ccs_two_var, ...
	causal_decoupling_ccs_two_var] = phiid_causal_emergence(all_atoms_err_coup_mmi_two_var, all_atoms_err_coup_ccs_two_var);

[synergy_capacity_mmi_three_var, ...
	downward_causation_mmi_three_var, ...
	causal_decoupling_mmi_three_var, ...
	synergy_capacity_ccs_three_var, ...
	downward_causation_ccs_three_var, ...
	causal_decoupling_ccs_three_var] = phiid_causal_emergence(all_atoms_err_coup_mmi_three_var, all_atoms_err_coup_ccs_three_var);

[synergy_capacity_mmi_four_var, ...
	downward_causation_mmi_four_var, ...
	causal_decoupling_mmi_four_var, ...
	synergy_capacity_ccs_four_var, ...
	downward_causation_ccs_four_var, ...
	causal_decoupling_ccs_four_var] = phiid_causal_emergence(all_atoms_err_coup_mmi_four_var, all_atoms_err_coup_ccs_four_var);

[synergy_capacity_mmi_five_var, ...
	downward_causation_mmi_five_var, ...
	causal_decoupling_mmi_five_var, ...
	synergy_capacity_ccs_five_var, ...
	downward_causation_ccs_five_var, ...
	causal_decoupling_ccs_five_var] = phiid_causal_emergence(all_atoms_err_coup_mmi_five_var, all_atoms_err_coup_ccs_five_var);

[synergy_capacity_mmi_six_var, ...
	downward_causation_mmi_six_var, ...
	causal_decoupling_mmi_six_var, ...
	synergy_capacity_ccs_six_var, ...
	downward_causation_ccs_six_var, ...
	causal_decoupling_ccs_six_var] = phiid_causal_emergence(all_atoms_err_coup_mmi_six_var, all_atoms_err_coup_ccs_six_var);

[synergy_capacity_mmi_seven_var, ...
	downward_causation_mmi_seven_var, ...
	causal_decoupling_mmi_seven_var, ...
	synergy_capacity_ccs_seven_var, ...
	downward_causation_ccs_seven_var, ...
	causal_decoupling_ccs_seven_var] = phiid_causal_emergence(all_atoms_err_coup_mmi_seven_var, all_atoms_err_coup_ccs_seven_var);

[synergy_capacity_mmi_eight_var, ...
	downward_causation_mmi_eight_var, ...
	causal_decoupling_mmi_eight_var, ...
	synergy_capacity_ccs_eight_var, ...
	downward_causation_ccs_eight_var, ...
	causal_decoupling_ccs_eight_var] = phiid_causal_emergence(all_atoms_err_coup_mmi_eight_var, all_atoms_err_coup_ccs_eight_var);


% save variables in a struct
[emergence_ccs_two_var, emergence_mmi_two_var, emergence_practical_two_var] = store_emergence_in_struct(synergy_capacity_mmi_two_var, ...
	causal_decoupling_mmi_two_var, downward_causation_mmi_two_var, synergy_capacity_ccs_two_var, ...
	causal_decoupling_ccs_two_var, downward_causation_ccs_two_var, synergy_capacity_practical_linear_two_var, ...
	causal_decoupling_practical_linear_two_var, downward_causation_practical_linear_two_var);

[emergence_ccs_three_var, emergence_mmi_three_var, emergence_practical_three_var] = store_emergence_in_struct(synergy_capacity_mmi_three_var, ...
	causal_decoupling_mmi_three_var, downward_causation_mmi_three_var, synergy_capacity_ccs_three_var, ...
	causal_decoupling_ccs_three_var, downward_causation_ccs_three_var, synergy_capacity_practical_linear_three_var, ...
	causal_decoupling_practical_linear_three_var, downward_causation_practical_linear_three_var);

[emergence_ccs_four_var, emergence_mmi_four_var, emergence_practical_four_var] = store_emergence_in_struct(synergy_capacity_mmi_four_var, ...
	causal_decoupling_mmi_four_var, downward_causation_mmi_four_var, synergy_capacity_ccs_four_var, ...
	causal_decoupling_ccs_four_var, downward_causation_ccs_four_var, synergy_capacity_practical_linear_four_var, ...
	causal_decoupling_practical_linear_four_var, downward_causation_practical_linear_four_var);
	
[emergence_ccs_five_var, emergence_mmi_five_var, emergence_practical_five_var] = store_emergence_in_struct(synergy_capacity_mmi_five_var, ...
	causal_decoupling_mmi_five_var, downward_causation_mmi_five_var, synergy_capacity_ccs_five_var, ...
	causal_decoupling_ccs_five_var, downward_causation_ccs_five_var, synergy_capacity_practical_linear_five_var, ...
	causal_decoupling_practical_linear_five_var, downward_causation_practical_linear_five_var);
	
[emergence_ccs_six_var, emergence_mmi_six_var, emergence_practical_six_var] = store_emergence_in_struct(synergy_capacity_mmi_six_var, ...
	causal_decoupling_mmi_six_var, downward_causation_mmi_six_var, synergy_capacity_ccs_six_var, ...
	causal_decoupling_ccs_six_var, downward_causation_ccs_six_var, synergy_capacity_practical_linear_five_var, ...
	causal_decoupling_practical_linear_five_var, downward_causation_practical_linear_five_var);
	
[emergence_ccs_seven_var, emergence_mmi_seven_var, emergence_practical_seven_var] = store_emergence_in_struct(synergy_capacity_mmi_seven_var, ...
	causal_decoupling_mmi_seven_var, downward_causation_mmi_seven_var, synergy_capacity_ccs_seven_var, ...
	causal_decoupling_ccs_seven_var, downward_causation_ccs_seven_var, synergy_capacity_practical_linear_seven_var, ...
	causal_decoupling_practical_linear_seven_var, downward_causation_practical_linear_seven_var);
	
[emergence_ccs_eight_var, emergence_mmi_eight_var, emergence_practical_eight_var] = store_emergence_in_struct(synergy_capacity_mmi_eight_var, ...
	causal_decoupling_mmi_eight_var, downward_causation_mmi_eight_var, synergy_capacity_ccs_eight_var, ...
	causal_decoupling_ccs_eight_var, downward_causation_ccs_eight_var, synergy_capacity_practical_linear_eight_var, ...
	causal_decoupling_practical_linear_eight_var, downward_causation_practical_linear_eight_var);

save([pathout_data network '_emergence_ccs_two_var_' sim_index '.mat'], 'emergence_ccs_two_var');
save([pathout_data network '_emergence_mmi_two_var_' sim_index '.mat'], 'emergence_mmi_two_var');
save([pathout_data network '_emergence_practical_two_var_' sim_index '.mat'], 'emergence_practical_two_var');

save([pathout_data network '_emergence_ccs_three_var_' sim_index '.mat'], 'emergence_ccs_three_var');
save([pathout_data network '_emergence_mmi_three_var_' sim_index '.mat'], 'emergence_mmi_three_var');
save([pathout_data network '_emergence_practical_three_var_' sim_index '.mat'], 'emergence_practical_three_var');

save([pathout_data network '_emergence_ccs_four_var_' sim_index '.mat'], 'emergence_ccs_four_var');
save([pathout_data network '_emergence_mmi_four_var_' sim_index '.mat'], 'emergence_mmi_four_var');
save([pathout_data network '_emergence_practical_four_var_' sim_index '.mat'], 'emergence_practical_four_var');

save([pathout_data network '_emergence_ccs_five_var_' sim_index '.mat'], 'emergence_ccs_five_var');
save([pathout_data network '_emergence_mmi_five_var_' sim_index '.mat'], 'emergence_mmi_five_var');
save([pathout_data network '_emergence_practical_five_var_' sim_index '.mat'], 'emergence_practical_five_var');

save([pathout_data network '_emergence_ccs_six_var_' sim_index '.mat'], 'emergence_ccs_six_var');
save([pathout_data network '_emergence_mmi_six_var_' sim_index '.mat'], 'emergence_mmi_six_var');
save([pathout_data network '_emergence_practical_six_var_' sim_index '.mat'], 'emergence_practical_six_var');

save([pathout_data network '_emergence_ccs_seven_var_' sim_index '.mat'], 'emergence_ccs_seven_var');
save([pathout_data network '_emergence_mmi_seven_var_' sim_index '.mat'], 'emergence_mmi_seven_var');
save([pathout_data network '_emergence_practical_seven_var_' sim_index '.mat'], 'emergence_practical_seven_var');

save([pathout_data network '_emergence_ccs_eight_var_' sim_index '.mat'], 'emergence_ccs_eight_var');
save([pathout_data network '_emergence_mmi_eight_var_' sim_index '.mat'], 'emergence_mmi_eight_var');
save([pathout_data network '_emergence_practical_eight_var_' sim_index '.mat'], 'emergence_practical_eight_var');
%}

%% plotting

% axes ticks
if sim_index == '3'
	x_axis = {'' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' ''  ... 
		'' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' };
	y_axis = {'' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' ''  ... 
		'' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' };
else
	x_axis = {'0.09', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '0.3', '', '', '', '', '', '', ... 
		'', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '0.6', '', '', '', '', '', '', '', '', '', '', '', '', '', ... 
		'', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '0.9', ''};
	y_axis = {'0.05', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '0.3', '', '', '', '', '', '', ... 
		'', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '0.6', '', '', '', '', '', '', '', '', '', '', '', '', '', ... 
		'', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '0.9', ''};
end 

% double-redundancy & double-synergy

% {
% heatmaps using imagesc()

atoms = {all_atoms_err_coup_ccs_two_var.rtr, ...
	all_atoms_err_coup_mmi_two_var.rtr, ...
	all_atoms_err_coup_ccs_two_var.sts, ...
	all_atoms_err_coup_mmi_two_var.sts, ...
	all_atoms_err_coup_ccs_three_var.rtr, ...
	all_atoms_err_coup_mmi_three_var.rtr, ...
	all_atoms_err_coup_ccs_three_var.sts, ...
	all_atoms_err_coup_mmi_three_var.sts, ...
	all_atoms_err_coup_ccs_four_var.rtr, ...
	all_atoms_err_coup_mmi_four_var.rtr, ...
	all_atoms_err_coup_ccs_four_var.sts, ...
	all_atoms_err_coup_mmi_four_var.sts, ...	
	all_atoms_err_coup_ccs_five_var.rtr, ...
	all_atoms_err_coup_mmi_five_var.rtr, ...
	all_atoms_err_coup_ccs_five_var.sts, ...
	all_atoms_err_coup_mmi_five_var.sts, ...
	all_atoms_err_coup_ccs_six_var.rtr, ...
	all_atoms_err_coup_mmi_six_var.rtr, ...
	all_atoms_err_coup_ccs_six_var.sts, ...
	all_atoms_err_coup_mmi_six_var.sts, ...
	all_atoms_err_coup_ccs_seven_var.rtr, ...
	all_atoms_err_coup_mmi_seven_var.rtr, ...
	all_atoms_err_coup_ccs_seven_var.sts, ...
	all_atoms_err_coup_mmi_seven_var.sts, ...
	all_atoms_err_coup_ccs_eight_var.rtr, ...
	all_atoms_err_coup_mmi_eight_var.rtr, ...
	all_atoms_err_coup_ccs_eight_var.sts, ...
	all_atoms_err_coup_mmi_eight_var.sts};

file_names = {'_all_err_coup_ccs_rtr_two_var', ...
	'_all_err_coup_mmi_rtr_two_var', ...
	'_all_err_coup_ccs_sts_two_var', ...
	'_all_err_coup_mmi_sts_two_var', ...
	'_all_err_coup_ccs_rtr_three_var', ...
	'_all_err_coup_mmi_rtr_three_var', ...
	'_all_err_coup_ccs_sts_three_var', ...
	'_all_err_coup_mmi_sts_three_var', ...
	'_all_err_coup_ccs_rtr_four_var', ...
	'_all_err_coup_mmi_rtr_four_var', ...
	'_all_err_coup_ccs_sts_four_var', ...
	'_all_err_coup_mmi_sts_four_var', ...
	'_all_err_coup_ccs_rtr_five_var', ...
	'_all_err_coup_mmi_rtr_five_var', ...
	'_all_err_coup_ccs_sts_five_var', ...
	'_all_err_coup_mmi_sts_five_var', ...
	'_all_err_coup_ccs_rtr_six_var', ...
	'_all_err_coup_mmi_rtr_six_var', ...
	'_all_err_coup_ccs_sts_six_var', ...
	'_all_err_coup_mmi_sts_six_var', ...
	'_all_err_coup_ccs_rtr_seven_var', ...
	'_all_err_coup_mmi_rtr_seven_var', ...
	'_all_err_coup_ccs_sts_seven_var', ...
	'_all_err_coup_mmi_sts_seven_var', ...
	'_all_err_coup_ccs_rtr_eight_var', ...
	'_all_err_coup_mmi_rtr_eight_var', ...
	'_all_err_coup_ccs_sts_eight_var', ...
	'_all_err_coup_mmi_sts_eight_var'};

titles = {
	'double-redundancy ccs two var', ...
	'double-redundancy mmi two var', ...
	'double-synergy ccs two var', ...
	'double-synergy mmi two var', ...
	'double-redundancy ccs three var', ...
	'double-redundancy mmi three var', ...
	'double-synergy ccs three var', ...
	'double-synergy mmi three var', ...
	'double-redundancy ccs four var', ...
	'double-redundancy mmi four var', ...
	'double-synergy ccs four var', ...
	'double-synergy mmi four var', ...
	'double-redundancy ccs five var', ...
	'double-redundancy mmi five var', ...
	'double-synergy ccs five var', ...
	'double-synergy mmi five var', ...
	'double-redundancy ccs six var', ...
	'double-redundancy mmi six var', ...
	'double-synergy ccs six var', ...
	'double-synergy mmi six var', ...
	'double-redundancy ccs seven var', ...
	'double-redundancy mmi seven var', ...
	'double-synergy ccs seven var', ...
	'double-synergy mmi seven var', ...
	'double-redundancy ccs eight var', ...
	'double-redundancy mmi eight var', ...
	'double-synergy ccs eight var', ...
	'double-synergy mmi eight var'};

% cmin = min([min(atoms{1}(:)), min(atoms{2}(:)), min(atoms{3}(:)), min(atoms{4}(:))]);
% cmax = max([max(atoms{1}(:)), max(atoms{2}(:)), max(atoms{3}(:)), max(atoms{4}(:))]);


for i = 1:size(atoms,2)

	figure;

	imagesc(atoms{i});
	colormap(bluewhitered); 
	colorbar;
	
	hColorbar = colorbar;
	set(hColorbar, 'Ticks', sort([hColorbar.Limits, hColorbar.Ticks]))

	xticks(1:size(x_axis, 2));
	yticks(1:size(y_axis, 2));
	set(gca,'TickLength',[0 0])
	yticklabels(y_axis);
	xticklabels(x_axis);
	
	if sim_index == '3';
		ylabel('zero coupling');
		xlabel('zero noise correlation');
	else 
		xlabel('noise correlation');
		ylabel('global coupling factor');
	end 
	
	title(titles{i});
	exportgraphics(gcf, [pathout_plots network file_names{i} sim_index '.png']);

end
%}

% synergistic capacity, downward causation, causal decoupling

% {
% heatmaps using imagesc()

atoms = {synergy_capacity_ccs_two_var, ...
	synergy_capacity_mmi_two_var, ...
	synergy_capacity_practical_linear_two_var, ...
	downward_causation_ccs_two_var, ...
	downward_causation_mmi_two_var, ...
	downward_causation_practical_linear_two_var, ...
	causal_decoupling_ccs_two_var, ...
	causal_decoupling_mmi_two_var, ...
	causal_decoupling_practical_linear_two_var, ...
	synergy_capacity_ccs_three_var, ...
	synergy_capacity_mmi_three_var, ...
	synergy_capacity_practical_linear_three_var, ...
	downward_causation_ccs_three_var, ...
	downward_causation_mmi_three_var, ...
	downward_causation_practical_linear_three_var, ...
	causal_decoupling_ccs_three_var, ...
	causal_decoupling_mmi_three_var, ...
	causal_decoupling_practical_linear_three_var, ...
	synergy_capacity_ccs_four_var, ...
	synergy_capacity_mmi_four_var, ...
	synergy_capacity_practical_linear_four_var, ...
	downward_causation_ccs_four_var, ...
	downward_causation_mmi_four_var, ...
	downward_causation_practical_linear_four_var, ...
	causal_decoupling_ccs_four_var, ...
	causal_decoupling_mmi_four_var, ...
	causal_decoupling_practical_linear_four_var, ...
	synergy_capacity_ccs_five_var, ...
	synergy_capacity_mmi_five_var, ...
	synergy_capacity_practical_linear_five_var, ...
	downward_causation_ccs_five_var, ...
	downward_causation_mmi_five_var, ...
	downward_causation_practical_linear_five_var, ...
	causal_decoupling_ccs_five_var, ...
	causal_decoupling_mmi_five_var, ...
	causal_decoupling_practical_linear_five_var, ...
	synergy_capacity_ccs_six_var, ...
	synergy_capacity_mmi_six_var, ...
	synergy_capacity_practical_linear_six_var, ...
	downward_causation_ccs_six_var, ...
	downward_causation_mmi_six_var, ...
	downward_causation_practical_linear_six_var, ...
	causal_decoupling_ccs_six_var, ...
	causal_decoupling_mmi_six_var, ...
	causal_decoupling_practical_linear_six_var, ...
	synergy_capacity_ccs_seven_var, ...
	synergy_capacity_mmi_seven_var, ...
	synergy_capacity_practical_linear_seven_var, ...
	downward_causation_ccs_seven_var, ...
	downward_causation_mmi_seven_var, ...
	downward_causation_practical_linear_seven_var, ...
	causal_decoupling_ccs_seven_var, ...
	causal_decoupling_mmi_seven_var, ...
	causal_decoupling_practical_linear_seven_var, ...
	synergy_capacity_ccs_eight_var, ...
	synergy_capacity_mmi_eight_var, ...
	synergy_capacity_practical_linear_eight_var, ...
	downward_causation_ccs_eight_var, ...
	downward_causation_mmi_eight_var, ...
	downward_causation_practical_linear_eight_var, ...
	causal_decoupling_ccs_eight_var, ...
	causal_decoupling_mmi_eight_var, ...
	causal_decoupling_practical_linear_eight_var, ...
	all_average_cov_X, ...
	all_average_corr_X};

file_names = {'_all_err_coup_ccs_synergy_capacity_two_var', ...
	'_all_err_coup_mmi_synergy_capacity_two_var',  ...
	'_all_err_coup_synergy_capacity_practical_linear_two_var', ...
	'_all_err_coup_ccs_downward_causation_two_var', ...
	'_all_err_coup_mmi_downward_causation_two_var', ...
	'_all_err_coup_downward_causation_practical_linear_two_var', ...
	'_all_err_coup_ccs_causal_decoupling_two_var', ...
	'_all_err_coup_mmi_causal_decoupling_two_var', ...
	'_all_err_coup_causal_decoupling_practical_linear_two_var', ...
	'_all_err_coup_ccs_synergy_capacity_three_var', ...
	'_all_err_coup_mmi_synergy_capacity_three_var',  ...
	'_all_err_coup_synergy_capacity_practical_linear_three_var', ...
	'_all_err_coup_ccs_downward_causation_three_var', ...
	'_all_err_coup_mmi_downward_causation_three_var', ...
	'_all_err_coup_downward_causation_practical_linear_three_var', ...
	'_all_err_coup_ccs_causal_decoupling_three_var', ...
	'_all_err_coup_mmi_causal_decoupling_three_var', ...
	'_all_err_coup_causal_decoupling_practical_linear_three_var', ...
	'_all_err_coup_ccs_synergy_capacity_four_var', ...
	'_all_err_coup_mmi_synergy_capacity_four_var',  ...
	'_all_err_coup_synergy_capacity_practical_linear_four_var', ...
	'_all_err_coup_ccs_downward_causation_four_var', ...
	'_all_err_coup_mmi_downward_causation_four_var', ...
	'_all_err_coup_downward_causation_practical_linear_four_var', ...
	'_all_err_coup_ccs_causal_decoupling_four_var', ...
	'_all_err_coup_mmi_causal_decoupling_four_var', ...
	'_all_err_coup_causal_decoupling_practical_linear_four_var', ...
	'_all_err_coup_ccs_synergy_capacity_five_var', ...
	'_all_err_coup_mmi_synergy_capacity_five_var',  ...
	'_all_err_coup_synergy_capacity_practical_linear_five_var', ...
	'_all_err_coup_ccs_downward_causation_five_var', ...
	'_all_err_coup_mmi_downward_causation_five_var', ...
	'_all_err_coup_downward_causation_practical_linear_five_var', ...
	'_all_err_coup_ccs_causal_decoupling_five_var', ...
	'_all_err_coup_mmi_causal_decoupling_five_var', ...
	'_all_err_coup_causal_decoupling_practical_linear_five_var', ...
	'_all_err_coup_ccs_synergy_capacity_six_var', ...
	'_all_err_coup_mmi_synergy_capacity_six_var',  ...
	'_all_err_coup_synergy_capacity_practical_linear_six_var', ...
	'_all_err_coup_ccs_downward_causation_six_var', ...
	'_all_err_coup_mmi_downward_causation_six_var', ...
	'_all_err_coup_downward_causation_practical_linear_six_var', ...
	'_all_err_coup_ccs_causal_decoupling_six_var', ...
	'_all_err_coup_mmi_causal_decoupling_six_var', ...
	'_all_err_coup_causal_decoupling_practical_linear_six_var', ...
	'_all_err_coup_ccs_synergy_capacity_seven_var', ...
	'_all_err_coup_mmi_synergy_capacity_seven_var',  ...
	'_all_err_coup_synergy_capacity_practical_linear_seven_var', ...
	'_all_err_coup_ccs_downward_causation_seven_var', ...
	'_all_err_coup_mmi_downward_causation_seven_var', ...
	'_all_err_coup_downward_causation_practical_linear_seven_var', ...
	'_all_err_coup_ccs_causal_decoupling_seven_var', ...
	'_all_err_coup_mmi_causal_decoupling_seven_var', ...
	'_all_err_coup_causal_decoupling_practical_linear_seven_var', ...
	'_all_err_coup_ccs_synergy_capacity_eight_var', ...
	'_all_err_coup_mmi_synergy_capacity_eight_var',  ...
	'_all_err_coup_synergy_capacity_practical_linear_eight_var', ...
	'_all_err_coup_ccs_downward_causation_eight_var', ...
	'_all_err_coup_mmi_downward_causation_eight_var', ...
	'_all_err_coup_downward_causation_practical_linear_eight_var', ...
	'_all_err_coup_ccs_causal_decoupling_eight_var', ...
	'_all_err_coup_mmi_causal_decoupling_eight_var', ...
	'_all_err_coup_causal_decoupling_practical_linear_eight_var', ...
	'_all_err_coup_average_cov_X', ...
	'_all_err_coup_average_corr_X'};

titles = {'synergy capacity ccs two var', ...
	'synergy capacity mmi two var', ...
	'synergy capacity practical linear two var', ...
	'downward causation ccs two var', ...
	'downward causation mmi two var', ...
	'downward causation practical linear two var', ...
	'causal decoupling ccs two var', ...
	'causal decoupling mmi two var', ...
	'causal decoupling practical linear two var', ...
	'synergy capacity ccs three var', ...
	'synergy capacity mmi three var', ...
	'synergy capacity practical linear three var', ...
	'downward causation ccs three var', ...
	'downward causation mmi three var', ...
	'downward causation practical linear three var', ...
	'causal decoupling ccs three var', ...
	'causal decoupling mmi three var', ...
	'causal decoupling practical linear three var', ...
	'synergy capacity ccs four var', ...
	'synergy capacity mmi four var', ...
	'synergy capacity practical linear four var', ...
	'downward causation ccs four var', ...
	'downward causation mmi four var', ...
	'downward causation practical linear four var', ...
	'causal decoupling ccs four var', ...
	'causal decoupling mmi four var', ...
	'causal decoupling practical linear four var', ...
	'synergy capacity ccs five var', ...
	'synergy capacity mmi five var', ...
	'synergy capacity practical linear five var', ...
	'downward causation ccs five var', ...
	'downward causation mmi five var', ...
	'downward causation practical linear five var', ...
	'causal decoupling ccs five var', ...
	'causal decoupling mmi five var', ...
	'causal decoupling practical linear five var', ...
	'synergy capacity ccs six var', ...
	'synergy capacity mmi six var', ...
	'synergy capacity practical linear six var', ...
	'downward causation ccs six var', ...
	'downward causation mmi six var', ...
	'downward causation practical linear six var', ...
	'causal decoupling ccs six var', ...
	'causal decoupling mmi six var', ...
	'causal decoupling practical linear six var', ...
	'synergy capacity ccs seven var', ...
	'synergy capacity mmi seven var', ...
	'synergy capacity practical linear seven var', ...
	'downward causation ccs seven var', ...
	'downward causation mmi seven var', ...
	'downward causation practical linear seven var', ...
	'causal decoupling ccs seven var', ...
	'causal decoupling mmi seven var', ...
	'causal decoupling practical linear seven var', ...
	'synergy capacity ccs eright var', ...
	'synergy capacity mmi eight var', ...
	'synergy capacity practical linear eight var', ...
	'downward causation ccs eight var', ... 
	'downward causation mmi eight var', ...
	'downward causation practical linear eight var', ...
	'causal decoupling ccs eight var', ...
	'causal decoupling mmi eight var', ...
	'causal decoupling practical linear eight var', ...
	'average covariance X', ...
	'average correlation X'};

for i = 1:size(atoms,2)
	
	figure;

	imagesc(atoms{i});
	colormap(bluewhitered); 
	colorbar;
	
	hColorbar = colorbar;
	set(hColorbar, 'Ticks', sort([hColorbar.Limits, hColorbar.Ticks]))
	
	xticks(1:size(x_axis, 2));
	yticks(1:size(y_axis, 2));

	set(gca,'TickLength',[0 0])
	yticklabels(y_axis);
	xticklabels(x_axis);
	
	if sim_index == '3'
		ylabel('zero coupling');
		xlabel('zero noise correlation');	
	else 
		xlabel('noise correlation');
		ylabel('global coupling factor');
	end 
	
	title(titles{i});
	exportgraphics(gcf, [pathout_plots network file_names{i} sim_index '.png']);

end
%}

close all;