function get_all_kuramoto_DD_heatmaps(network, taus, all_npoints, x_axis, y_axis, x_label, y_label, ...
		pathout_data_dd, pathout_plots_dd_mean_pair_sync, pathout_plots_dd_sigma_chi, ...
		pathout_plots_dd_pair_sync, pathout_plots_dd_synchrony, pathout_plots_dd_control_vars)

	set(0,'DefaultFigureVisible','off');
	
	for q = 1:length(all_npoints);
		npoints = all_npoints(q);
		
		for z = 1:length(taus);
			tau = taus(z);
			
			load([pathout_data_dd network '_DD_' num2str(npoints) '_' num2str(tau) '.mat'], ...
				'DD');
			
			% DD for different micro variables, macro: mean pairwise synchrony
			variables = {DD.dd_phase_mean_pair_sync, ...
				DD.dd_raw_signal_mean_pair_sync, ...
				DD.dd_synchrony_mean_pair_sync, ...
				DD.dd_pair_sync_mean_pair_sync};
			
			file_names = {'dd_phase_mean_pair_sync', ...
				'dd_raw_signal_mean_pair_sync', ...
				'dd_synchrony_mean_pair_sync', ...
				'dd_pair_sync_mean_pair_sync'};
			
			titles = {{['DD, macro: mean pairwise sync, micro: phase'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}, ...
				{['DD, macro: mean pairwise sync, micro: raw signal'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}, ...
				{['DD, macro: mean pairwise sync, micro: sync'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}, ...
				{['DD, macro: mean pairwise sync, micro: pair sync'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}};
			
			plot_heatmap(variables, file_names, titles, x_axis, y_axis, x_label, y_label, network, npoints, ...
				pathout_plots_dd_mean_pair_sync, tau);
			
			% DD for different micro variables, macro: sigma chi
			variables = {DD.dd_phase_sigma_chi, ...
				DD.dd_raw_signal_sigma_chi, ...
				DD.dd_synchrony_sigma_chi, ...
				DD.dd_pair_sync_sigma_chi};
			
			file_names = {'dd_phase_sigma_chi', ...
				'dd_raw_signal_sigma_chi', ...
				'dd_synchrony_sigma_chi', ...
				'dd_pair_sync_sigma_chi'};
			
			titles = {{['DD, macro: sigma chi, micro: phase'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}, ...
				{['DD, macro: sigma chi, micro: raw signal'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}, ...
				{['DD, macro: sigma chi, micro: sync'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}, ...
				{['DD, macro: sigma chi, micro: pair sync'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}};
			
			plot_heatmap(variables, file_names, titles, x_axis, y_axis, x_label, y_label, network, npoints, ...
			pathout_plots_dd_sigma_chi, tau);
		
			% DD for different micro variables, macro: synchronies
			
			variables = {DD.dd_phase_synchrony, ...
				DD.dd_raw_signal_synchrony};
			
			file_names = {'dd_phase_synchrony', ...
				'dd_raw_signal_synchrony'};
			
			titles = {{['DD, macro: synchrony, micro: phase'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}, ...
				{['DD, macro: synchrony, micro: raw signal'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}};
			
			plot_heatmap(variables, file_names, titles, x_axis, y_axis, x_label, y_label, network, npoints, ...
			pathout_plots_dd_synchrony, tau);
		
			% DD for different micro variables, macro: pairwise synchronies
			
			variables = {DD.dd_phase_pair_sync, ...
				DD.dd_raw_signal_pair_sync};
			
			file_names = {'dd_phase_pair_sync', ...
				'dd_raw_signal_pair_sync'};
			
			titles = {{['DD, macro: pairwise synchrony, micro: phase'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}, ...
				{['DD, macro: pairwise synchrony, micro: raw signal'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}};
			
			plot_heatmap(variables, file_names, titles, x_axis, y_axis, x_label, y_label, network, npoints, ...
			pathout_plots_dd_pair_sync, tau);
		
			% DD for shuffled micro variables and top-level sigma chi
			variables = {DD.dd_phase_shuffled_sigma_chi, ...
				DD.dd_raw_signal_shuffled_sigma_chi, ...
				DD.dd_synchrony_shuffled_sigma_chi, ...
				DD.dd_pair_sync_shuffled_sigma_chi, ...
				DD.dd_shuffled_phase_sigma_chi, ...
				DD.dd_shuffled_phase_mean_pair_sync, ...
				DD.dd_shuffled_phase_shuffled_sigma_chi};
			
			file_names = {'dd_phase_shuffled_sigma_chi', ...
				'dd_raw_signal_shuffled_sigma_chi', ...
				'dd_synchrony_shuffled_sigma_chi', ...
				'dd_pair_sync_shuffled_sigma_chi', ...
				'dd_shuffled_phase_sigma_chi', ...
				'dd_shuffled_phase_mean_pair_sync', ...
				'dd_shuffled_phase_shuffled_sigma_chi'};
			
			titles = {{['DD, macro: shuffled sigma chi, micro: phase'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}, ...
				{['DD, macro: shuffled sigma chi, micro: raw signal'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}, ...
				{['DD, macro: shuffled sigma chi, micro: synchrony'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}, ...
				{['DD, macro: shuffled sigma chi, micro: pairwise synchrony'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}, ...
				{['DD, macro: sigma chi, micro: shuffled phase'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}, ...
				{['DD, macro: mean pair sync, micro: shuffled phase'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}, ...
				{['DD, macro: shuffled sigma chi, micro: shuffled phase'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}};
			
			plot_heatmap(variables, file_names, titles, x_axis, y_axis, x_label, y_label, network, npoints, ...
				pathout_plots_dd_control_vars, tau);
		end 
	end 
end