function get_all_kuramoto_practCE_heatmaps(network, taus, all_npoints, x_axis, y_axis, x_label, y_label, pathout_data_pract_ce, ...
		pathout_plots_pract_ce_mean_pair_sync, pathout_plots_pract_ce_sigma_chi, pathout_plots_pract_ce_control_vars)

	set(0,'DefaultFigureVisible','off');
	
	for q = 1:length(all_npoints);
		npoints = all_npoints(q);
		
		for z = 1:length(taus);
			tau = taus(z);
			
			load([pathout_data_pract_ce network '_practCE_' num2str(npoints) '_' num2str(tau) '.mat'], ...
				'practCE');
			
			% practical CE, DC, & CD for different micro variables, macro: mean pairwise synchrony
			variables = {practCE.pract_ce_bin_phase_bin_mean_pair_sync, ...
				practCE.pract_ce_bin_raw_signal_bin_mean_pair_sync, ...
				practCE.pract_ce_bin_synchrony_bin_mean_pair_sync, ...
				practCE.pract_ce_bin_pair_sync_bin_mean_pair_sync, ...
				practCE.pract_dc_bin_phase_bin_mean_pair_sync, ...
				practCE.pract_dc_bin_raw_signal_bin_mean_pair_sync, ...
				practCE.pract_dc_bin_synchrony_bin_mean_pair_sync, ...
				practCE.pract_dc_bin_pair_sync_bin_mean_pair_sync, ...
				practCE.pract_cd_bin_phase_bin_mean_pair_sync, ...
				practCE.pract_cd_bin_raw_signal_bin_mean_pair_sync, ...
				practCE.pract_cd_bin_synchrony_bin_mean_pair_sync, ...
				practCE.pract_cd_bin_pair_sync_bin_mean_pair_sync};	
			
			file_names = {'pract_ce_bin_phase_bin_mean_pair_sync', ...
				'pract_ce_bin_raw_signal_bin_mean_pair_sync', ...
				'pract_ce_bin_synchrony_bin_mean_pair_sync', ...
				'practCE.pract_ce_bin_pair_sync_bin_mean_pair_sync', ...
				'pract_dc_bin_phase_bin_mean_pair_sync', ...
				'pract_dc_bin_raw_signal_bin_mean_pair_sync', ...
				'pract_dc_bin_synchrony_bin_mean_pair_sync', ...
				'pract_dc_bin_pair_sync_bin_mean_pair_sync', ...
				'pract_cd_bin_phase_bin_mean_pair_sync', ...
				'pract_cd_bin_raw_signal_bin_mean_pair_sync', ...
				'pract_cd_bin_synchrony_bin_mean_pair_sync', ...
				'pract_cd_bin_pair_sync_bin_mean_pair_sync'};
			
			titles = {{['practical CE, macro: mean pairwise sync, micro: phase'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}, ...
				{['practical CE, macro: mean pairwise sync, micro: raw signal'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}, ...
				{['practical CE, macro: mean pairwise sync, micro: sync'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}, ...
				{['practical CE, macro: mean pairwise sync, micro: pair sync'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}, ...
				{['practical DC, macro: mean pairwise sync, micro: phase'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}, ...
				{['practical DC, macro: mean pairwise sync, micro: raw signal'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}, ...
				{['practical DC, macro: mean pairwise sync, micro: sync'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}, ...
				{['practical DC, macro: mean pairwise sync, micro: pair sync'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}, ...
				{['practical CD, macro: mean pairwise sync, micro: phase'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}, ...
				{['practical CD, macro: mean pairwise sync, micro: raw signal'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}, ...
				{['practical CD, macro: mean pairwise sync, micro: sync'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}, ...
				{['practical CD, macro: mean pairwise sync, micro: pair sync'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}};
			
			plot_heatmap(variables, file_names, titles, x_axis, y_axis, x_label, y_label, network, npoints, ...
				pathout_plots_pract_ce_mean_pair_sync, tau);
			
			% practical CE, DC, & CD for different micro variables, macro: sigma chi
			variables = {practCE.pract_ce_bin_phase_bin_sigma_chi, ...
				practCE.pract_ce_bin_raw_signal_bin_sigma_chi, ...
				practCE.pract_ce_bin_synchrony_bin_sigma_chi, ...
				practCE.pract_ce_bin_pair_sync_bin_sigma_chi, ...
				practCE.pract_dc_bin_phase_bin_sigma_chi, ...
				practCE.pract_dc_bin_raw_signal_bin_sigma_chi, ...
				practCE.pract_dc_bin_synchrony_bin_sigma_chi, ...
				practCE.pract_dc_bin_pair_sync_bin_sigma_chi, ...
				practCE.pract_cd_bin_phase_bin_sigma_chi, ...
				practCE.pract_cd_bin_raw_signal_bin_sigma_chi, ...
				practCE.pract_cd_bin_synchrony_bin_sigma_chi, ...
				practCE.pract_cd_bin_pair_sync_bin_sigma_chi};
			
			file_names = {'pract_ce_bin_phase_bin_sigma_chi', ...
				'pract_ce_bin_raw_signal_bin_sigma_chi', ...
				'pract_ce_bin_synchrony_bin_sigma_chi', ...
				'pract_ce_bin_pair_sync_bin_sigma_chi', ...
				'pract_dc_bin_phase_bin_sigma_chi', ...
				'pract_dc_bin_raw_signal_bin_sigma_chi', ...
				'pract_dc_bin_synchrony_bin_sigma_chi', ...
				'pract_dc_bin_pair_sync_bin_sigma_chi', ...
				'pract_cd_bin_phase_bin_sigma_chi', ...
				'pract_cd_bin_raw_signal_bin_sigma_chi', ...
				'pract_cd_bin_synchrony_bin_sigma_chi', ...
				'pract_cd_bin_pair_sync_bin_sigma_chi'};
			
			titles = {{['practical CE, macro: sigma chi, micro: phase'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}, ...
				{['practical CE, macro: sigma chi, micro: raw signal'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}, ...
				{['practical CE, macro: sigma chi, micro: sync'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}, ...
				{['practical CE, macro: sigma chi, micro: pair sync'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}, ...
				{['practical DC, macro: sigma chi, micro: phase'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}, ...
				{['practical DC, macro: sigma chi, micro: raw signal'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}, ...
				{['practical DC, macro: sigma chi, micro: sync'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}, ...
				{['practical DC, macro: sigma chi, micro: pair sync'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}, ...
				{['practical CD, macro: sigma chi, micro: phase'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}, ...
				{['practical CD, macro: sigma chi, micro: raw signal'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}, ...
				{['practical CD, macro: sigma chi, micro: sync'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}, ...
				{['practical CD, macro: sigma chi, micro: pair sync'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}};
			
			plot_heatmap(variables, file_names, titles, x_axis, y_axis, x_label, y_label, network, npoints, ...
			pathout_plots_pract_ce_sigma_chi, tau);
		
			% practical CE, DC, & CD for shuffled phase and (shuffled) macro variables
			
			variables = {practCE.pract_ce_bin_shuffled_phase_bin_sigma_chi, ...
				practCE.pract_ce_bin_shuffled_phase_bin_mean_pair_sync, ...
				practCE.pract_ce_bin_shuffled_phase_bin_shuffled_sigma_chi, ...
				practCE.pract_dc_bin_shuffled_phase_bin_sigma_chi, ...
				practCE.pract_dc_bin_shuffled_phase_bin_mean_pair_sync, ...
				practCE.pract_dc_bin_shuffled_phase_bin_shuffled_sigma_chi, ...
				practCE.pract_cd_bin_shuffled_phase_bin_sigma_chi, ...
				practCE.pract_cd_bin_shuffled_phase_bin_mean_pair_sync, ...
				practCE.pract_cd_bin_shuffled_phase_bin_shuffled_sigma_chi};
		
			file_names = {'pract_ce_bin_shuffled_phase_bin_sigma_chi', ...
				'pract_ce_bin_shuffled_phase_bin_mean_pair_sync', ...
				'pract_ce_bin_shuffled_phase_bin_shuffled_sigma_chi', ...
				'pract_dc_bin_shuffled_phase_bin_sigma_chi', ...
				'pract_dc_bin_shuffled_phase_bin_mean_pair_sync', ...
				'pract_dc_bin_shuffled_phase_bin_shuffled_sigma_chi', ...
				'pract_cd_bin_shuffled_phase_bin_sigma_chi', ...
				'pract_cd_bin_shuffled_phase_bin_mean_pair_sync', ...
				'pract_cd_bin_shuffled_phase_bin_shuffled_sigma_chi'};
				
			titles = {{['practical CE, macro: sigma chi, micro: shuffled phase'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}, ...
				{['practical CE, macro: mean pairwise sync, micro: shuffled phase'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}, ...
				{['practical CE, macro: shuffled sigma chi, micro: shuffled phase'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}, ...
				{['practical DC, macro: sigma chi, micro: shuffled phase'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}, ...
				{['practical DC, macro: mean pairwise sync, micro: shuffled phase'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}, ...
				{['practical DC, macro: shuffled sigma chi, micro: shuffled phase'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}, ...
				{['practical CD, macro: sigma chi, micro: shuffled phase'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}, ...
				{['practical CD, macro: mean pairwise sync, micro: shuffled phase'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}, ...
				{['practical CD, macro: shuffled sigma chi, micro: shuffled phase'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}};
			
			plot_heatmap(variables, file_names, titles, x_axis, y_axis, x_label, y_label, network, npoints, ...
				pathout_plots_pract_ce_control_vars, tau);
			
			% practical CE, DC, & CD for micro variables and shuffled sigma chi
			
			variables = {practCE.pract_ce_bin_phase_bin_shuffled_sigma_chi, ...
				practCE.pract_ce_bin_raw_signal_bin_shuffled_sigma_chi, ...
				practCE.pract_ce_bin_synchrony_bin_shuffled_sigma_chi, ...
				practCE.pract_ce_bin_pair_sync_bin_shuffled_sigma_chi, ...
				practCE.pract_dc_bin_phase_bin_shuffled_sigma_chi, ...
				practCE.pract_dc_bin_raw_signal_bin_shuffled_sigma_chi, ...
				practCE.pract_dc_bin_synchrony_bin_shuffled_sigma_chi, ...
				practCE.pract_dc_bin_pair_sync_bin_shuffled_sigma_chi, ...
				practCE.pract_cd_bin_phase_bin_shuffled_sigma_chi, ...
				practCE.pract_cd_bin_raw_signal_bin_shuffled_sigma_chi, ...
				practCE.pract_cd_bin_synchrony_bin_shuffled_sigma_chi, ...
				practCE.pract_cd_bin_pair_sync_bin_shuffled_sigma_chi};
			
			file_names = {'pract_ce_bin_phase_bin_shuffled_sigma_chi', ...
				'pract_ce_bin_raw_signal_bin_shuffled_sigma_chi', ...
				'pract_ce_bin_synchrony_bin_shuffled_sigma_chi', ...
				'pract_ce_bin_pair_sync_bin_shuffled_sigma_chi', ...
				'pract_dc_bin_phase_bin_shuffled_sigma_chi', ...
				'pract_dc_bin_raw_signal_bin_shuffled_sigma_chi', ...
				'pract_dc_bin_synchrony_bin_shuffled_sigma_chi', ...
				'pract_dc_bin_pair_sync_bin_shuffled_sigma_chi', ...
				'pract_cd_bin_phase_bin_shuffled_sigma_chi', ...
				'pract_cd_bin_raw_signal_bin_shuffled_sigma_chi', ...
				'pract_cd_bin_synchrony_bin_shuffled_sigma_chi', ...
				'pract_cd_bin_pair_sync_bin_shuffled_sigma_chi'};
			
			titles = {{['practical CE, macro: shuffled sigma chi, micro: phase'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}, ...
				{['practical CE, macro: shuffled sigma chi, micro: raw signal'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}, ...
				{['practical CE, macro: shuffled sigma chi, micro: synchrony'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}, ...
				{['practical CE, macro: shuffled sigma chi, micro: pairwise synchrony'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}, ...
				{['practical DC, macro: shuffled sigma chi, micro: shuffled phase'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}, ...
				{['practical DC, macro: shuffled sigma chi, micro: shuffled phase'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}, ...
				{['practical DC, macro: shuffled sigma chi, micro: shuffled phase'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}, ...
				{['practical DC, macro: shuffled sigma chi, micro: pairwise synchrony'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}, ...
				{['practical CD, macro: shuffled sigma chi, micro: shuffled phase'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}, ...
				{['practical CD, macro: shuffled sigma chi, micro: shuffled phase'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}, ...
				{['practical CD, macro: shuffled sigma chi, micro: shuffled phase'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}, ...
				{['practical CD, macro: shuffled sigma chi, micro: pairwise synchrony'] ['npoints = ' num2str(npoints) ', tau = ' num2str(tau)]}};
				
			plot_heatmap(variables, file_names, titles, x_axis, y_axis, x_label, y_label, network, npoints, ...
				pathout_plots_pract_ce_control_vars, tau);
		
		end
	end
	
end 