function get_all_kuramoto_corr_heatmaps(network, all_npoints, x_axis, y_axis, x_label, y_label, ...
		pathout_data_mean_corr, pathout_plots_mean_corr)

	for q = 1:length(all_npoints);
		npoints = all_npoints(q);
		
		set(0,'DefaultFigureVisible','off');
		
		% micro variables
		load([pathout_data_mean_corr network '_mean_corr_phase_' num2str(npoints) '.mat'], ...
			'mean_corr_phase');
		load([pathout_data_mean_corr network '_mean_corr_raw_signal_' num2str(npoints) '.mat'], ...
			'mean_corr_raw_signal');
		load([pathout_data_mean_corr network '_mean_corr_synchrony_' num2str(npoints) '.mat'], ...
			'mean_corr_synchrony');
		load([pathout_data_mean_corr network 'mean_corr_pair_sync_' num2str(npoints) '.mat'], ...
			'mean_corr_pair_sync');
		
		% micro and macro variables
		
		% phase + macro variables
		load([pathout_data_mean_corr network '_mean_corr_phase_sigma_chi_' num2str(npoints) '.mat'], ...
			'mean_corr_phase_sigma_chi');
		load([pathout_data_mean_corr network '_mean_corr_phase_pair_sync_' num2str(npoints) '.mat'], ...
			'mean_corr_phase_pair_sync');
		load([pathout_data_mean_corr network '_mean_corr_phase_mean_pair_sync_' num2str(npoints) '.mat'], ...
			'mean_corr_phase_mean_pair_sync');
		load([pathout_data_mean_corr network '_mean_corr_phase_synchrony_' num2str(npoints) '.mat'], ...
			'mean_corr_phase_synchrony');
		
		% raw signal + macro variables
		load([pathout_data_mean_corr network '_mean_corr_raw_signal_sigma_chi_' num2str(npoints) '.mat'], ...
			'mean_corr_raw_signal_sigma_chi');
		load([pathout_data_mean_corr network '_mean_corr_raw_signal_pair_sync_' num2str(npoints) '.mat'], ...
			'mean_corr_raw_signal_pair_sync');
		load([pathout_data_mean_corr network '_mean_corr_raw_signal_mean_pair_sync_' num2str(npoints) '.mat'], ...
			'mean_corr_raw_signal_mean_pair_sync');
		load([pathout_data_mean_corr network '_mean_corr_raw_signal_synchrony_' num2str(npoints) '.mat'], ...
			'mean_corr_raw_signal_synchrony');
		
		% synchrony + macro variables
		load([pathout_data_mean_corr network '_mean_corr_synchrony_sigma_chi_' num2str(npoints) '.mat'], ...
			'mean_corr_synchrony_sigma_chi');
		load([pathout_data_mean_corr network '_mean_corr_synchrony_mean_pair_sync_' num2str(npoints) '.mat'], ...
			'mean_corr_synchrony_mean_pair_sync');

		% pairwise synchrony + macro variables
		load([pathout_data_mean_corr network '_mean_corr_pair_sync_sigma_chi_' num2str(npoints) '.mat'], ...
			'mean_corr_pair_sync_sigma_chi');
		load([pathout_data_mean_corr network '_mean_corr_pair_sync_mean_pair_sync_' num2str(npoints) '.mat'], ...
			'mean_corr_pair_sync_mean_pair_sync');
		
		variables = {mean_corr_phase, ...
			mean_corr_raw_signal, ...
			mean_corr_synchrony, ...
			mean_corr_pair_sync, ...
			mean_corr_phase_sigma_chi, ...
			mean_corr_phase_mean_pair_sync, ...
			mean_corr_phase_pair_sync, ...
			mean_corr_phase_synchrony, ...
			mean_corr_raw_signal_sigma_chi, ...
			mean_corr_raw_signal_mean_pair_sync, ...
			mean_corr_raw_signal_pair_sync, ...
			mean_corr_raw_signal_synchrony, ...
			mean_corr_synchrony_sigma_chi, ...
			mean_corr_synchrony_mean_pair_sync, ...
			mean_corr_pair_sync_sigma_chi, ...
			mean_corr_pair_sync_mean_pair_sync};
		
		file_names = {'mean_corr_phase', ...
			'mean_corr_raw_signal', ...
			'mean_corr_synchrony', ...
			'mean_corr_pair_sync', ...
			'mean_corr_phase_sigma_chi', ...
			'mean_corr_phase_mean_pair_sync', ...
			'mean_corr_phase_pair_sync', ...
			'mean_corr_phase_synchrony', ...
			'mean_corr_raw_signal_sigma_chi', ...
			'mean_corr_raw_signal_mean_pair_sync', ...
			'mean_corr_raw_signal_pair_sync', ...
			'mean_corr_raw_signal_synchrony', ...
			'mean_corr_synchrony_sigma_chi', ...
			'mean_corr_synchrony_mean_pair_sync', ...
			'mean_corr_pair_sync_sigma_chi', ...
			'mean_corr_pair_sync_mean_pair_sync'};
		
		titles = {{['mean correlation of phases'] ['npoints = ' num2str(npoints)]}, ...
			{['mean correlation of raw signals'] ['npoints = ' num2str(npoints)]}, ...
			{['mean correlation of synchronies'] ['npoints = ' num2str(npoints)]}, ...
			{['mean correlation of pairwise synchronies'] ['npoints = ' num2str(npoints)]}, ...
			{['mean correlation of phases & sigma chi'] ['npoints = ' num2str(npoints)]}, ...
			{['mean correlation of phases & mean pairwise synchrony'] ['npoints = ' num2str(npoints)]}, ...
			{['mean correlation of phases & pairwise synchrony'] ['npoints = ' num2str(npoints)]}, ...
			{['mean correlation of phases & synchrony'] ['npoints = ' num2str(npoints)]}, ...
			{['mean correlation of raw signal & sigma chi'] ['npoints = ' num2str(npoints)]}, ...
			{['mean correlation of raw signal & mean pairwise synchrony'] ['npoints = ' num2str(npoints)]}, ...
			{['mean correlation of raw signal & pairwise synchrony'] ['npoints = ' num2str(npoints)]}, ...
			{['mean correlation of raw signal & synchrony'] ['npoints = ' num2str(npoints)]}, ...
			{['mean correlation of synchronies & sigma chi'] ['npoints = ' num2str(npoints)]}, ...
			{['mean correlation of synchronies & mean pairwise synchrony'] ['npoints = ' num2str(npoints)]}, ...
			{['mean correlation of pairwise synchronies & sigma chi'] ['npoints = ' num2str(npoints)]}, ...
			{['mean correlation of pairwise synchronies & mean pairwise synchrony'] ['npoints = ' num2str(npoints)]}};
		
		plot_heatmap(variables, file_names, titles, x_axis, y_axis, x_label, y_label, network, npoints, pathout_plots_mean_corr);
	end 

end 